#!/bin/bash

OS_TRIGGER_FILE=/tmp/os_trigger
WATCH_DELAY=2

test -n "${OS_VERSION}" || source /etc/init.d/base

function log() {
    logger -t ostrigger "$1"
}

function watch() {
    sleep ${WATCH_DELAY}
    
    while true; do
        sleep ${WATCH_DELAY}
        test -s ${OS_TRIGGER_FILE} || continue
        read -r line < ${OS_TRIGGER_FILE}
        rm -f ${OS_TRIGGER_FILE}
        if [[ "${line}" == reboot ]]; then
            log "rebooting"
            reboot
            break
        elif [[ "${line}" == poweroff ]]; then
            log "poweroff"
            poweroff
            break
        elif [[ "${line}" == compose-pull ]]; then
            log "compose-pull"
            service dockercompose pull
        else
            log "unknown trigger command: ${line}"
        fi
    done
}

function start() {
    msg_begin "Starting ostrigger"
    watch &
    msg_done
}

function stop() {
    msg_begin "Stopping ostrigger"
    ps | grep "ostrigger" | grep -v $$ | grep -v grep | tr -s ' ' | sed -e 's/^\s//' | cut -d ' ' -f 1 | xargs -r kill
    msg_done
}

case "$1" in
    start)
        start
        ;;
        
    stop)
        stop
        ;;
        
    restart)
        stop
        start
        ;;
    
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
