#!/bin/bash

OK_LED=LED3

function turn_on() {
    echo 1 > /sys/class/leds/${OK_LED}/brightness
}

function turn_off() {
    echo 0 > /sys/class/leds/${OK_LED}/brightness
}

function is_docker_compose_pulling() {
    ps aux | grep -v grep | grep -qE "docker.*compose.*pull" &>/dev/null
}

function watch_pull() {
    pull=false
    blink_on=0
    while true; do
        if is_docker_compose_pulling; then
            pull=true
            test ${blink_on} == 1 && turn_off || turn_on
            blink_on=$(( 1- blink_on ))
            usleep 500000
        else
            pull=false
            turn_on
            sleep 1
        fi
    done
}


case "$1" in
    start)
        turn_off
        watch_pull &
        ;;

    stop)
        ps | grep okled | grep -v $$ | grep -v grep | tr -s ' ' | sed -e 's/^\s//' | cut -d ' ' -f 1 | xargs -r kill
        turn_off
        ;;

    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit $?
