#!/bin/bash

if [[ "$1" == "get" ]]; then
    echo "QS_NAME=$(/bin/hostname)"
elif [[ "$1" == "set" ]]; then
    test -n "${QS_NAME}" || exit 0
    echo "${QS_NAME}" > /host/data/etc/hostname
    /bin/hostname ${QS_NAME}
    echo "127.0.0.1 localhost ${QS_NAME}" > /host/etc/hosts
fi
