#!/bin/bash

if [[ "$1" == "handle" ]]; then
    echo "QS_VALUE=$(cat /host/data/etc/remote | cut -d : -f 1)"
elif [[ "$1" == "password" ]]; then
    echo "QS_VALUE=$(cat /host/data/etc/remote | cut -d : -f 2)"
fi
